version: 1.0.0.{build}
branches:
  only:
  - master
skip_tags: true
image: Visual Studio 2019
configuration: Release
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  version_prefix: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
build_script:
- ps: >-
    dotnet restore src/HomeAutio.Mqtt.Denon.sln

    dotnet publish -c Release src/HomeAutio.Mqtt.Denon.sln
artifacts:
- path: src\HomeAutio.Mqtt.Denon\bin\$(configuration)\netcoreapp3.1\publish
  name: HomeAutio.Mqtt.Denon-$(appveyor_build_version)
deploy:
- provider: GitHub
  auth_token:
    secure: t8wH1tV0xPU25FeKde96GGBYZIcWVhBy7VuIJujTodtx1FSQzlI0AEOPHLKyPORa
  artifact: src\HomeAutio.Mqtt.Denon\bin\$(configuration)\netcoreapp3.1\HomeAutio.Mqtt.Denon-$(appveyor_build_version).zip
  force_update: false